default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: hatch run lint:check
        language: system
        pass_filenames: false
        files: ^(gocream_pycdek/.*\.py|pyproject\.toml)$
        stages: [pre-commit]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
